services:
  - type: web
    name: arbitrage-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    branch: main
    autoDeploy: true
